type: object
properties:
  _embedded:
    type: object
    properties:
      environments:
        type: array
        items:
          allOf:
            - $ref: >-
                ./com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
          title: Environments Collection Response _embedded Environment
        title: Environments Collection Response _embedded Environments
    title: Environments Collection Response _embedded
  _links:
    type: object
    properties:
      next:
        $ref: ./com.pingidentity.api.response.Link.yaml
      prev:
        $ref: ./com.pingidentity.api.response.Link.yaml
      self:
        $ref: ./com.pingidentity.api.response.Link.yaml
    additionalProperties:
      $ref: ./com.pingidentity.api.response.Link.yaml
    title: Environments Collection Response _links
  count:
    type: integer
    format: int32
    title: Environments Collection Response Count
  size:
    type: integer
    format: int32
    title: Environments Collection Response Size
title: Environments Collection Response
