type: object
additionalProperties: true
properties:
  name:
    pattern: ^(?=\S)[\p{L}\p{M}\p{N}\p{So}/.'_ -]*(?!.*((<)|(\$\{)))
    maxLength: 256
    type: string
    minLength: 1
    title: DaVinci Application Create Request Name
required:
  - name
title: DaVinci Application Create Request
