get:
  operationId: getDavinciApplicationById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.davinciApplications.davinciApplicationID.yaml
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  responses:
    '200':
      description: Successful Operation.
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.davinci.applications.response.ApplicationResponse.yaml
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.P14C63085.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.yaml
    '415':
      $ref: ../components/responses/http.415.UnsupportedMediaType.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: davinci:read:applications
  tags:
    - DaVinci Admin Applications
    - DaVinci Admin APIs
    - PingOne DaVinci
put:
  operationId: replaceDavinciApplicationById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.davinciApplications.davinciApplicationID.yaml
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/com.pingidentity.pingone.davinci.applications.data.UpdateApplication.yaml
    required: true
  responses:
    '200':
      description: Successful Operation.
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.davinci.applications.response.ApplicationResponse.yaml
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.P14C63085.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.yaml
    '415':
      $ref: ../components/responses/http.415.UnsupportedMediaType.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: davinci:update:applications
  tags:
    - DaVinci Admin Applications
    - DaVinci Admin APIs
    - PingOne DaVinci
delete:
  operationId: deleteDavinciApplicationById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.davinciApplications.davinciApplicationID.yaml
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  responses:
    '204':
      description: Successfully removed. No content.
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.P14C63085.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.yaml
    '415':
      $ref: ../components/responses/http.415.UnsupportedMediaType.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: davinci:delete:applications
  tags:
    - DaVinci Admin Applications
    - DaVinci Admin APIs
    - PingOne DaVinci
